ablation_iterations_restarts_1:
  name: patchesswap
  restarts: 50
  max_patches: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_2:
  name: patchesswap
  restarts: 100
  max_patches: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_3:
  name: patchesswap
  restarts: 250
  max_patches: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_restarts_4:
  name: patchesswap
  restarts: 500
  max_patches: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: false
ablation_iterations_iterative_1:
  name: patchesswap
  max_patches: 50
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_2:
  name: patchesswap
  max_patches: 100
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_3:
  name: patchesswap
  max_patches: 250
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_4:
  name: patchesswap
  max_patches: 500
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_5:
  name: patchesswap
  max_patches: 1000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_6:
  name: patchesswap
  max_patches: 2000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true
ablation_iterations_iterative_7:
  name: patchesswap
  max_patches: 10000
  x_dimensions: 1
  y_dimensions: 1
  save_images: false
  load: true
  pixel_mapping: random
  update_each_iteration: true