attack4:
  name: patchesswap
  population: 10
  same_size: false
attack1:
  name: patchesswap
attack2:
  name: patchesswap
  population: 1
attack3:
  name: patchesswap
  population: 10
onepixel1:
  name: onepixel
  pixels: 1
onepixel2:
  name: onepixel
  pixels: 3
onepixel3:
  name: onepixel
  pixels: 5
fgsm1:
  name: fgsm
  eps: 0.01
fgsm2:
  name: fgsm
  eps: 0.1
fgsm3:
  name: fgsm
  eps: 1
fgsm4:
  name: fgsm
  eps: 3
square1:
  name: square
  eps: 0.1
square2:
  name: square
  eps: 0.05
square3:
  name: square
  eps: 0.01