scratch_1line:
  name: scratch_that
  pupulation: 50
  max_iterations: 50
  mutation_rate: 0.8
  crossover: 0.7
  save_images: true
scratch_2line:
  name: scratch_that
  n_scratches: 2
  pupulation: 50
  max_iterations: 50
  mutation_rate: 0.8
  crossover: 0.7
  save_images: true
scratch_1bezier:
  name: scratch_that
  pupulation: 50
  max_iterations: 50
  mutation_rate: 0.8
  crossover: 0.7
  scratch_type: bezier
  save_images: true
scratch_2bezier:
  name: scratch_that
  pupulation: 50
  max_iterations: 50
  mutation_rate: 0.8
  crossover: 0.7
  scratch_type: bezier
  save_images: true
scratch_3bezier:
  name: scratch_that
  pupulation: 50
  max_iterations: 50
  mutation_rate: 0.8
  crossover: 0.7
  scratch_type: bezier
  save_images: true

